# Generated by Django 3.1.2 on 2020-11-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorProducto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=60)),
                ('descripcion', models.TextField(max_length=200)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
